export interface Project {
  id: string;
  name: string;
  title: string;
  category: string;
  shortTitle: string;
  shortLabel?: string;
  subtitle?: string;
  oneLinePurpose?: string;
  description: string;
  fullDescription?: string;
  technologies: string[];
  tags: string[];
  features: string[];
  keyWins: string[];
  technicalFocus?: string[];
  githubUrl: string;
  apiRepoUrl?: string;
  liveUrl?: string | null;
  featured: boolean;
  isCompanion?: boolean;
  companionProject?: string;
  companionUrl?: string;
  status: string;
  accuracyNote?: string;
  windowFile: string;
  image: string;
  accent: string;
  hudTitle: string;
  hudSub: string;
  hudBadge: string;
  architecture?: {
    frontend?: string;
    routing?: string;
    stateManagement?: string;
    http?: string;
    ui?: string;
    apiData?: string;
  };
}
